//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: Classes/com/google/j2objc/LibraryNotLinkedError.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleJ2objcLibraryNotLinkedError")
#ifdef RESTRICT_ComGoogleJ2objcLibraryNotLinkedError
#define INCLUDE_ALL_ComGoogleJ2objcLibraryNotLinkedError 0
#else
#define INCLUDE_ALL_ComGoogleJ2objcLibraryNotLinkedError 1
#endif
#undef RESTRICT_ComGoogleJ2objcLibraryNotLinkedError

#if !defined (ComGoogleJ2objcLibraryNotLinkedError_) && (INCLUDE_ALL_ComGoogleJ2objcLibraryNotLinkedError || defined(INCLUDE_ComGoogleJ2objcLibraryNotLinkedError))
#define ComGoogleJ2objcLibraryNotLinkedError_

#define RESTRICT_JavaLangError 1
#define INCLUDE_JavaLangError 1
#include "java/lang/Error.h"

@class IOSObjectArray;
@class JavaLangThrowable;

/*!
 @brief Thrown when a class is requested that is part of a J2ObjC JRE library
  which wasn't linked into the application.
 */
@interface ComGoogleJ2objcLibraryNotLinkedError : JavaLangError

#pragma mark Public

/*!
 @brief Create a new LibraryNotLinkedException.
 @param functionalName the Java functionality that was requested
 @param libraryName the name of the J2ObjC JRE library that was not linked
 @param dependencyClassName the class to statically reference to force linking
 */
- (instancetype)initWithNSString:(NSString *)functionalName
                    withNSString:(NSString *)libraryName
                    withNSString:(NSString *)dependencyClassName;

/*!
 @brief Create a new LibraryNotLinkedException.
 @param functionalName the Java functionality that was requested
 @param libraryName the name of the J2ObjC JRE library that was not linked
 @param dependencyClassName the class to statically reference to force linking
 @param addedText text to be appended to the exception message
 @param args any values to be used when formatting the addedText string.
 */
- (instancetype)initWithNSString:(NSString *)functionalName
                    withNSString:(NSString *)libraryName
                    withNSString:(NSString *)dependencyClassName
                    withNSString:(NSString *)addedText
               withNSObjectArray:(IOSObjectArray *)args;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)arg0 NS_UNAVAILABLE;

- (instancetype)initWithNSString:(NSString *)arg0 NS_UNAVAILABLE;

- (instancetype)initWithNSString:(NSString *)arg0
           withJavaLangThrowable:(JavaLangThrowable *)arg1 NS_UNAVAILABLE;

- (instancetype)initWithNSString:(NSString *)arg0
           withJavaLangThrowable:(JavaLangThrowable *)arg1
                     withBoolean:(jboolean)arg2
                     withBoolean:(jboolean)arg3 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleJ2objcLibraryNotLinkedError)

FOUNDATION_EXPORT void ComGoogleJ2objcLibraryNotLinkedError_initWithNSString_withNSString_withNSString_(ComGoogleJ2objcLibraryNotLinkedError *self, NSString *functionalName, NSString *libraryName, NSString *dependencyClassName);

FOUNDATION_EXPORT ComGoogleJ2objcLibraryNotLinkedError *new_ComGoogleJ2objcLibraryNotLinkedError_initWithNSString_withNSString_withNSString_(NSString *functionalName, NSString *libraryName, NSString *dependencyClassName) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleJ2objcLibraryNotLinkedError *create_ComGoogleJ2objcLibraryNotLinkedError_initWithNSString_withNSString_withNSString_(NSString *functionalName, NSString *libraryName, NSString *dependencyClassName);

FOUNDATION_EXPORT void ComGoogleJ2objcLibraryNotLinkedError_initWithNSString_withNSString_withNSString_withNSString_withNSObjectArray_(ComGoogleJ2objcLibraryNotLinkedError *self, NSString *functionalName, NSString *libraryName, NSString *dependencyClassName, NSString *addedText, IOSObjectArray *args);

FOUNDATION_EXPORT ComGoogleJ2objcLibraryNotLinkedError *new_ComGoogleJ2objcLibraryNotLinkedError_initWithNSString_withNSString_withNSString_withNSString_withNSObjectArray_(NSString *functionalName, NSString *libraryName, NSString *dependencyClassName, NSString *addedText, IOSObjectArray *args) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleJ2objcLibraryNotLinkedError *create_ComGoogleJ2objcLibraryNotLinkedError_initWithNSString_withNSString_withNSString_withNSString_withNSObjectArray_(NSString *functionalName, NSString *libraryName, NSString *dependencyClassName, NSString *addedText, IOSObjectArray *args);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleJ2objcLibraryNotLinkedError)

#endif

#pragma pop_macro("INCLUDE_ALL_ComGoogleJ2objcLibraryNotLinkedError")
