//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/frameworks/base/core/java/com/google/android/collect/Lists.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleAndroidCollectLists")
#ifdef RESTRICT_ComGoogleAndroidCollectLists
#define INCLUDE_ALL_ComGoogleAndroidCollectLists 0
#else
#define INCLUDE_ALL_ComGoogleAndroidCollectLists 1
#endif
#undef RESTRICT_ComGoogleAndroidCollectLists

#if !defined (ComGoogleAndroidCollectLists_) && (INCLUDE_ALL_ComGoogleAndroidCollectLists || defined(INCLUDE_ComGoogleAndroidCollectLists))
#define ComGoogleAndroidCollectLists_

@class IOSObjectArray;
@class JavaUtilArrayList;

/*!
 @brief Provides static methods for creating <code>List</code> instances easily, and other
  utility methods for working with lists.
 */
@interface ComGoogleAndroidCollectLists : NSObject

#pragma mark Public

- (instancetype)init;

/*!
 @brief Creates an empty <code>ArrayList</code> instance.
 <p><b>Note:</b> if you only need an <i>immutable</i> empty List, use 
 <code>Collections.emptyList</code> instead.
 @return a newly-created, initially-empty <code>ArrayList</code>
 */
+ (JavaUtilArrayList *)newArrayList OBJC_METHOD_FAMILY_NONE;

/*!
 @brief Creates a resizable <code>ArrayList</code> instance containing the given
  elements.
 <p><b>Note:</b> due to a bug in javac 1.5.0_06, we cannot support the
  following: 
 <p><code>List<Base> list = Lists.newArrayList(sub1, sub2);</code>
  
 <p>where <code>sub1</code> and <code>sub2</code> are references to subtypes of 
 <code>Base</code>, not of <code>Base</code> itself. To get around this, you must
  use: 
 <p><code>List<Base> list = Lists.<Base>newArrayList(sub1, sub2);</code>
 @param elements the elements that the list should contain, in order
 @return a newly-created <code>ArrayList</code> containing those elements
 */
+ (JavaUtilArrayList *)newArrayListWithNSObjectArray:(IOSObjectArray *)elements OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleAndroidCollectLists)

FOUNDATION_EXPORT void ComGoogleAndroidCollectLists_init(ComGoogleAndroidCollectLists *self);

FOUNDATION_EXPORT ComGoogleAndroidCollectLists *new_ComGoogleAndroidCollectLists_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleAndroidCollectLists *create_ComGoogleAndroidCollectLists_init(void);

FOUNDATION_EXPORT JavaUtilArrayList *ComGoogleAndroidCollectLists_newArrayList(void);

FOUNDATION_EXPORT JavaUtilArrayList *ComGoogleAndroidCollectLists_newArrayListWithNSObjectArray_(IOSObjectArray *elements);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleAndroidCollectLists)

#endif

#pragma pop_macro("INCLUDE_ALL_ComGoogleAndroidCollectLists")
