//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/frameworks/base/core/java/com/google/android/collect/Maps.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleAndroidCollectMaps")
#ifdef RESTRICT_ComGoogleAndroidCollectMaps
#define INCLUDE_ALL_ComGoogleAndroidCollectMaps 0
#else
#define INCLUDE_ALL_ComGoogleAndroidCollectMaps 1
#endif
#undef RESTRICT_ComGoogleAndroidCollectMaps

#if !defined (ComGoogleAndroidCollectMaps_) && (INCLUDE_ALL_ComGoogleAndroidCollectMaps || defined(INCLUDE_ComGoogleAndroidCollectMaps))
#define ComGoogleAndroidCollectMaps_

@class AndroidUtilArrayMap;
@class JavaUtilHashMap;

/*!
 @brief Provides static methods for creating mutable <code>Maps</code> instances easily.
 */
@interface ComGoogleAndroidCollectMaps : NSObject

#pragma mark Public

- (instancetype)init;

/*!
 @brief Creates a <code>ArrayMap</code> instance.
 */
+ (AndroidUtilArrayMap *)newArrayMap OBJC_METHOD_FAMILY_NONE;

/*!
 @brief Creates a <code>HashMap</code> instance.
 @return a newly-created, initially-empty <code>HashMap</code>
 */
+ (JavaUtilHashMap *)newHashMap OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleAndroidCollectMaps)

FOUNDATION_EXPORT void ComGoogleAndroidCollectMaps_init(ComGoogleAndroidCollectMaps *self);

FOUNDATION_EXPORT ComGoogleAndroidCollectMaps *new_ComGoogleAndroidCollectMaps_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleAndroidCollectMaps *create_ComGoogleAndroidCollectMaps_init(void);

FOUNDATION_EXPORT JavaUtilHashMap *ComGoogleAndroidCollectMaps_newHashMap(void);

FOUNDATION_EXPORT AndroidUtilArrayMap *ComGoogleAndroidCollectMaps_newArrayMap(void);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleAndroidCollectMaps)

#endif

#pragma pop_macro("INCLUDE_ALL_ComGoogleAndroidCollectMaps")
