//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/frameworks/base/core/java/android/util/ContainerHelpers.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidUtilContainerHelpers")
#ifdef RESTRICT_AndroidUtilContainerHelpers
#define INCLUDE_ALL_AndroidUtilContainerHelpers 0
#else
#define INCLUDE_ALL_AndroidUtilContainerHelpers 1
#endif
#undef RESTRICT_AndroidUtilContainerHelpers

#if !defined (AndroidUtilContainerHelpers_) && (INCLUDE_ALL_AndroidUtilContainerHelpers || defined(INCLUDE_AndroidUtilContainerHelpers))
#define AndroidUtilContainerHelpers_

@class IOSBooleanArray;
@class IOSIntArray;
@class IOSLongArray;
@class IOSObjectArray;

@interface AndroidUtilContainerHelpers : NSObject

#pragma mark Package-Private

- (instancetype)init;

+ (jint)binarySearchWithIntArray:(IOSIntArray *)array
                         withInt:(jint)size
                         withInt:(jint)value;

+ (jint)binarySearchWithLongArray:(IOSLongArray *)array
                          withInt:(jint)size
                         withLong:(jlong)value;

@end

J2OBJC_STATIC_INIT(AndroidUtilContainerHelpers)

inline IOSBooleanArray *AndroidUtilContainerHelpers_get_EMPTY_BOOLEANS(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT IOSBooleanArray *AndroidUtilContainerHelpers_EMPTY_BOOLEANS;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidUtilContainerHelpers, EMPTY_BOOLEANS, IOSBooleanArray *)

inline IOSIntArray *AndroidUtilContainerHelpers_get_EMPTY_INTS(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT IOSIntArray *AndroidUtilContainerHelpers_EMPTY_INTS;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidUtilContainerHelpers, EMPTY_INTS, IOSIntArray *)

inline IOSLongArray *AndroidUtilContainerHelpers_get_EMPTY_LONGS(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT IOSLongArray *AndroidUtilContainerHelpers_EMPTY_LONGS;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidUtilContainerHelpers, EMPTY_LONGS, IOSLongArray *)

inline IOSObjectArray *AndroidUtilContainerHelpers_get_EMPTY_OBJECTS(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT IOSObjectArray *AndroidUtilContainerHelpers_EMPTY_OBJECTS;
J2OBJC_STATIC_FIELD_OBJ_FINAL(AndroidUtilContainerHelpers, EMPTY_OBJECTS, IOSObjectArray *)

FOUNDATION_EXPORT void AndroidUtilContainerHelpers_init(AndroidUtilContainerHelpers *self);

FOUNDATION_EXPORT AndroidUtilContainerHelpers *new_AndroidUtilContainerHelpers_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AndroidUtilContainerHelpers *create_AndroidUtilContainerHelpers_init(void);

FOUNDATION_EXPORT jint AndroidUtilContainerHelpers_binarySearchWithIntArray_withInt_withInt_(IOSIntArray *array, jint size, jint value);

FOUNDATION_EXPORT jint AndroidUtilContainerHelpers_binarySearchWithLongArray_withInt_withLong_(IOSLongArray *array, jint size, jlong value);

J2OBJC_TYPE_LITERAL_HEADER(AndroidUtilContainerHelpers)

#endif

#pragma pop_macro("INCLUDE_ALL_AndroidUtilContainerHelpers")
