//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/platform/libcore/dalvik/src/main/java/dalvik/system/BlockGuard.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_DalvikSystemBlockGuard")
#ifdef RESTRICT_DalvikSystemBlockGuard
#define INCLUDE_ALL_DalvikSystemBlockGuard 0
#else
#define INCLUDE_ALL_DalvikSystemBlockGuard 1
#endif
#undef RESTRICT_DalvikSystemBlockGuard

#if !defined (DalvikSystemBlockGuard_) && (INCLUDE_ALL_DalvikSystemBlockGuard || defined(INCLUDE_DalvikSystemBlockGuard))
#define DalvikSystemBlockGuard_

@protocol DalvikSystemBlockGuard_Policy;

/*!
 @brief Mechanism to let threads set restrictions on what code is allowed
  to do in their thread.
 <p>This is meant for applications to prevent certain blocking
  operations from running on their main event loop (or "UI") threads. 
 <p>Note that this is all best-effort to catch most accidental mistakes
  and isn't intended to be a perfect mechanism, nor provide any sort of
  security.
 */
@interface DalvikSystemBlockGuard : NSObject

#pragma mark Public

/*!
 @brief Get the current thread's policy.
 @return the current thread's policy.  Never returns null.
      Will return the LAX_POLICY instance if nothing else is set.
 */
+ (id<DalvikSystemBlockGuard_Policy>)getThreadPolicy;

/*!
 @brief Sets the current thread's block guard policy.
 @param policy policy to set.  May not be null.  Use the public LAX_POLICY    if you want to unset the active policy.
 */
+ (void)setThreadPolicyWithDalvikSystemBlockGuard_Policy:(id<DalvikSystemBlockGuard_Policy>)policy;

@end

J2OBJC_STATIC_INIT(DalvikSystemBlockGuard)

inline jint DalvikSystemBlockGuard_get_DISALLOW_DISK_WRITE(void);
#define DalvikSystemBlockGuard_DISALLOW_DISK_WRITE 1
J2OBJC_STATIC_FIELD_CONSTANT(DalvikSystemBlockGuard, DISALLOW_DISK_WRITE, jint)

inline jint DalvikSystemBlockGuard_get_DISALLOW_DISK_READ(void);
#define DalvikSystemBlockGuard_DISALLOW_DISK_READ 2
J2OBJC_STATIC_FIELD_CONSTANT(DalvikSystemBlockGuard, DISALLOW_DISK_READ, jint)

inline jint DalvikSystemBlockGuard_get_DISALLOW_NETWORK(void);
#define DalvikSystemBlockGuard_DISALLOW_NETWORK 4
J2OBJC_STATIC_FIELD_CONSTANT(DalvikSystemBlockGuard, DISALLOW_NETWORK, jint)

inline jint DalvikSystemBlockGuard_get_PASS_RESTRICTIONS_VIA_RPC(void);
#define DalvikSystemBlockGuard_PASS_RESTRICTIONS_VIA_RPC 8
J2OBJC_STATIC_FIELD_CONSTANT(DalvikSystemBlockGuard, PASS_RESTRICTIONS_VIA_RPC, jint)

inline jint DalvikSystemBlockGuard_get_PENALTY_LOG(void);
#define DalvikSystemBlockGuard_PENALTY_LOG 16
J2OBJC_STATIC_FIELD_CONSTANT(DalvikSystemBlockGuard, PENALTY_LOG, jint)

inline jint DalvikSystemBlockGuard_get_PENALTY_DIALOG(void);
#define DalvikSystemBlockGuard_PENALTY_DIALOG 32
J2OBJC_STATIC_FIELD_CONSTANT(DalvikSystemBlockGuard, PENALTY_DIALOG, jint)

inline jint DalvikSystemBlockGuard_get_PENALTY_DEATH(void);
#define DalvikSystemBlockGuard_PENALTY_DEATH 64
J2OBJC_STATIC_FIELD_CONSTANT(DalvikSystemBlockGuard, PENALTY_DEATH, jint)

/*!
 @brief The default, permissive policy that doesn't prevent any operations.
 */
inline id<DalvikSystemBlockGuard_Policy> DalvikSystemBlockGuard_get_LAX_POLICY(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT id<DalvikSystemBlockGuard_Policy> DalvikSystemBlockGuard_LAX_POLICY;
J2OBJC_STATIC_FIELD_OBJ_FINAL(DalvikSystemBlockGuard, LAX_POLICY, id<DalvikSystemBlockGuard_Policy>)

FOUNDATION_EXPORT id<DalvikSystemBlockGuard_Policy> DalvikSystemBlockGuard_getThreadPolicy(void);

FOUNDATION_EXPORT void DalvikSystemBlockGuard_setThreadPolicyWithDalvikSystemBlockGuard_Policy_(id<DalvikSystemBlockGuard_Policy> policy);

J2OBJC_TYPE_LITERAL_HEADER(DalvikSystemBlockGuard)

#endif

#if !defined (DalvikSystemBlockGuard_Policy_) && (INCLUDE_ALL_DalvikSystemBlockGuard || defined(INCLUDE_DalvikSystemBlockGuard_Policy))
#define DalvikSystemBlockGuard_Policy_

@protocol DalvikSystemBlockGuard_Policy < JavaObject >

/*!
 @brief Called on disk writes.
 */
- (void)onWriteToDisk;

/*!
 @brief Called on disk reads.
 */
- (void)onReadFromDisk;

/*!
 @brief Called on network operations.
 */
- (void)onNetwork;

/*!
 @brief Returns the policy bitmask, for shipping over Binder calls
  to remote threads/processes and reinstantiating the policy
  there.The bits in the mask are from the DISALLOW_* and
  PENALTY_* constants.
 */
- (jint)getPolicyMask;

@end

J2OBJC_EMPTY_STATIC_INIT(DalvikSystemBlockGuard_Policy)

J2OBJC_TYPE_LITERAL_HEADER(DalvikSystemBlockGuard_Policy)

#endif

#if !defined (DalvikSystemBlockGuard_BlockGuardPolicyException_) && (INCLUDE_ALL_DalvikSystemBlockGuard || defined(INCLUDE_DalvikSystemBlockGuard_BlockGuardPolicyException))
#define DalvikSystemBlockGuard_BlockGuardPolicyException_

#define RESTRICT_JavaLangRuntimeException 1
#define INCLUDE_JavaLangRuntimeException 1
#include "java/lang/RuntimeException.h"

@class JavaLangThrowable;

@interface DalvikSystemBlockGuard_BlockGuardPolicyException : JavaLangRuntimeException

#pragma mark Public

- (instancetype)initWithInt:(jint)policyState
                    withInt:(jint)policyViolated;

- (instancetype)initWithInt:(jint)policyState
                    withInt:(jint)policyViolated
               withNSString:(NSString *)message;

- (NSString *)getMessage;

- (jint)getPolicy;

- (jint)getPolicyViolation;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)arg0 NS_UNAVAILABLE;

- (instancetype)initWithNSString:(NSString *)arg0 NS_UNAVAILABLE;

- (instancetype)initWithNSString:(NSString *)arg0
           withJavaLangThrowable:(JavaLangThrowable *)arg1 NS_UNAVAILABLE;

- (instancetype)initWithNSString:(NSString *)arg0
           withJavaLangThrowable:(JavaLangThrowable *)arg1
                     withBoolean:(jboolean)arg2
                     withBoolean:(jboolean)arg3 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(DalvikSystemBlockGuard_BlockGuardPolicyException)

FOUNDATION_EXPORT void DalvikSystemBlockGuard_BlockGuardPolicyException_initWithInt_withInt_(DalvikSystemBlockGuard_BlockGuardPolicyException *self, jint policyState, jint policyViolated);

FOUNDATION_EXPORT DalvikSystemBlockGuard_BlockGuardPolicyException *new_DalvikSystemBlockGuard_BlockGuardPolicyException_initWithInt_withInt_(jint policyState, jint policyViolated) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT DalvikSystemBlockGuard_BlockGuardPolicyException *create_DalvikSystemBlockGuard_BlockGuardPolicyException_initWithInt_withInt_(jint policyState, jint policyViolated);

FOUNDATION_EXPORT void DalvikSystemBlockGuard_BlockGuardPolicyException_initWithInt_withInt_withNSString_(DalvikSystemBlockGuard_BlockGuardPolicyException *self, jint policyState, jint policyViolated, NSString *message);

FOUNDATION_EXPORT DalvikSystemBlockGuard_BlockGuardPolicyException *new_DalvikSystemBlockGuard_BlockGuardPolicyException_initWithInt_withInt_withNSString_(jint policyState, jint policyViolated, NSString *message) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT DalvikSystemBlockGuard_BlockGuardPolicyException *create_DalvikSystemBlockGuard_BlockGuardPolicyException_initWithInt_withInt_withNSString_(jint policyState, jint policyViolated, NSString *message);

J2OBJC_TYPE_LITERAL_HEADER(DalvikSystemBlockGuard_BlockGuardPolicyException)

#endif

#pragma pop_macro("INCLUDE_ALL_DalvikSystemBlockGuard")
